# Generated by Django 3.0.5 on 2020-08-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_class_1_class_10_class_2_class_3_class_4_class_5_class_6_class_7_class_8_class_9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_1',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='class_10',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='class_2',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='class_3',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='class_4',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='class_5',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='class_6',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='class_7',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='class_8',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='class_9',
            name='file_link',
        ),
        migrations.AddField(
            model_name='class_1',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_1/'),
        ),
        migrations.AddField(
            model_name='class_10',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_10/'),
        ),
        migrations.AddField(
            model_name='class_2',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_2/'),
        ),
        migrations.AddField(
            model_name='class_3',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_3/'),
        ),
        migrations.AddField(
            model_name='class_4',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_4/'),
        ),
        migrations.AddField(
            model_name='class_5',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_5/'),
        ),
        migrations.AddField(
            model_name='class_6',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_6/'),
        ),
        migrations.AddField(
            model_name='class_7',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_7/'),
        ),
        migrations.AddField(
            model_name='class_8',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_8/'),
        ),
        migrations.AddField(
            model_name='class_9',
            name='file_upload',
            field=models.FileField(default='', upload_to='class_9/'),
        ),
    ]
