# Generated by Django 3.0.5 on 2020-10-22 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20200831_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_1',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_10',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_2',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_3',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_4',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_5',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_6',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_7',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_8',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_9',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='class_1',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_1',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_10',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_10',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_2',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_2',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_3',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_3',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_4',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_4',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_5',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_5',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_6',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_6',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_7',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_7',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_8',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_8',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_9',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('Others', 'Others')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='class_9',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class_1',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_1/'),
        ),
        migrations.AlterField(
            model_name='class_10',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_10/'),
        ),
        migrations.AlterField(
            model_name='class_2',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_2/'),
        ),
        migrations.AlterField(
            model_name='class_3',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_3/'),
        ),
        migrations.AlterField(
            model_name='class_4',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_4/'),
        ),
        migrations.AlterField(
            model_name='class_5',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_5/'),
        ),
        migrations.AlterField(
            model_name='class_6',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_6/'),
        ),
        migrations.AlterField(
            model_name='class_7',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_7/'),
        ),
        migrations.AlterField(
            model_name='class_8',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_8/'),
        ),
        migrations.AlterField(
            model_name='class_9',
            name='file_upload',
            field=models.FileField(blank=True, default='', upload_to='class_9/'),
        ),
    ]
