# Generated by Django 3.0.5 on 2021-04-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20201022_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_1',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_10',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_2',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_3',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_4',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_5',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_6',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_7',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_8',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='class_9',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='class_1',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='class_10',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='class_2',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='class_3',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='class_4',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='class_5',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='class_6',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='class_7',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='class_8',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='class_9',
            name='file_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
